export const SET_ROOM_NAME = 'SET_ROOM_NAME';
export const SET_ROOM_DESC = 'SET_ROOM_DESC';
export const CREATE_ROOM_START = 'CREATE_ROOM_START';
export const CREATE_ROOM_FAILURE = 'CREATE_ROOM_FAILURE';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_STORY_START = 'CREATE_STORY_START';
export const CREATE_STORY_FAILURE = 'CREATE_STORY_FAILURE';
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';
