export const CREATE_STORY_START = 'CREATE_STORY_START';
export const CREATE_STORY_FAILURE = 'CREATE_STORY_FAILURE';
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';
export const ADD_NAME = 'ADD_NAME';
export const ADD_DESCRIPTION = 'ADD_DESCRIPTION';
